### ISSUE TITLE
해당 작업 필요할 듯 합니다.

### ISSUE THREAD

**Issue by jeangho293** [Link-Gather/link-gather-nest#51]
1. await 누락
https://github.com/Link-Gather/link-gather-nest/blob/2868d57b09c9a02a8be54026ace2bc347858e789/src/services/auth/presentation/controller.ts#L167

2. verification 이 undefined일 때 에러메세지 필요
https://github.com/Link-Gather/link-gather-nest/blob/c3a7acb404be73df05751de66c07ded46dc748ea/src/services/verifications/domain/specs/valid-verification-spec.ts#L14-L26

**Comment by yoon-bomi** [comment]
> verification 이 undefined일 때 에러메세지 필요

이게 어떤 경우이죠? 어떤 에러메세지를 보내주면 되나요? @changchanghwang 
작업은 제가 하겠습니다.

**Comment by changchanghwang** [comment]
걍 findOneOrFail로 바꿔주세요

**Comment by changchanghwang** [comment]
verification없으면 그냥 return []해주세요.

없는경우 에러메세지 보낼필요 없습니다.

**Comment by yoon-bomi** [comment]
@changchanghwang PR 올렸습니다.

https://github.com/Link-Gather/link-gather-nest/pull/53
